### ISSUE TITLE
I cannot expose PointCloud2/Image topics  

### ISSUE THREAD

**Issue by dimrakan** [uts-magic-lab/rosduct#2]
I am able to expose JointState,String,Odometry message topics from a docker container but when i  
i am trying to expose PointCloud2/Image message topics,  i am getting no messages in my local topics,
 and I am getting this error.
Exception in thread WebSocketClient:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.target(self.args, **self.kwargs)
  File "build/bdist.linux-x86_64/egg/ws4py/websocket.py", line 524, in run
    if not self.once():
  File "build/bdist.linux-x86_64/egg/ws4py/websocket.py", line 406, in once
    if not self.process(self.buf):
  File "build/bdist.linux-x86_64/egg/ws4py/websocket.py", line 476, in process
    self.received_message(s.message)
  File "/home/test/rosduct_ws/src/rosduct/src/rosduct/rosbridge_client.py", line 452, in received_message
    dispatcher.send(signal=data.get('topic'), message=data.get('msg'))
  File "build/bdist.linux-x86_64/egg/pydispatch/dispatcher.py", line 338, in send
    **named
  File "build/bdist.linux-x86_64/egg/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(arguments, **named)
  File "/home/test/rosduct_ws/src/rosduct/src/rosduct/rosduct_impl.py", line 220, in callback_remote_to_local
    rospub.publish(msg)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 886, in publish
    raise ROSSerializationException(str(e))
ROSSerializationException: field header.frame_id is a unicode string instead of an ascii string

**Comment by awesomebytes** [comment]
Your error is in the end, you can't use Unicode text in a frame_id. Well, a
quick Google have me this workarounds:

https://answers.ros.org/question/269873/how-do-i-use-unicode-strings-in-pubishsubscribe/

Official explanation can be found here:
http://wiki.ros.org/msg

(Search for unicode).

Mainly, whoever is publishing that pointcloud needs to change the frame_id
to have a string that is not unicode.
